server:
  listen_host: 0.0.0.0
  listen_port: 8378
redis:
  host: redis
  port: 6379
  password: ""
hasura:
  url: ws://nginx:8185/v1/graphql
graphql-actions:
  url: http://bbb-graphql-actions:8093
auth_hook:
  url: http://bbb-web:8090/bigbluebutton/connection/checkGraphqlAuthorization
session_vars_hook:
  url: http://apps-akka:8901/userInfo