#!/bin/bash

# https://github.com/bigbluebutton/bigbluebutton/pull/9597/files

CONTAINER_ID=$(docker ps | grep freeswitch | awk '{print $1}')
docker exec -it $CONTAINER_ID fs_cli -H 10.7.7.1 -P 8021 -x 'fsctl sync_clock_when_idle'