#!/bin/bash
set -e

cd $(dirname $0)/..

# load .env
. functions.sh
load_env

if [ ! "$ENABLE_RECORDING" == true ]; then
  echo "Error: recording is disabled why can't use bbb-record"
  echo "set ENABLE_RECORDING in .env if you want to use it"
  exit 1
fi

docker compose exec recordings bbb-record $@
docker compose logs --tail=15 recordings