#!/bin/bash

set -e
cd "$(dirname "$0")/.."

# load .env
. scripts/functions.sh
load_env

if [ -z "$ENABLE_WEBHOOKS" ]; then
    echo "ERROR: ENABLE_WEBHOOKS must be set to true, otherwise the image would not be built"
    exit 1
fi

if [ -z "$ENABLE_RECORDING" ]; then
    echo "ERROR: ENABLE_RECORDING must be set to true, otherwise the image would not be built"
    exit 1
fi


# generate compose file
./scripts/generate-compose

# ensure submodules are correctly checked out
git submodule update  

# build and push java base image
docker build -t alangecker/bbb-docker-base-java:latest mod/base-java

# buld and push other images
docker compose build

# push images
docker push alangecker/bbb-docker-base-java:latest
docker compose push \
    apps-akka \
    bbb-export-annotations \
    bbb-graphql-actions \
    bbb-graphql-middleware \
    bbb-graphql-server \
    bbb-pads \
    bbb-web \
    bbb-webrtc-recorder \
    etherpad \
    fsesl-akka \
    haproxy \
    nginx \
    periodic \
    recordings \
    webhooks \
    webrtc-sfu \
    freeswitch
