#!/bin/bash

set -e
cd $(dirname $0)/..

if [ -z $RESTARTED ]
then

    echo "# pull newest bigblugbutton-docker.git"
    git pull

    # restart script, since it might have changed.
    RESTARTED=1 ./scripts/upgrade-and-build
    exit

else

    echo ""
    echo "# pull newest git submodules"
    ./scripts/checkout-submodules

    echo ""
    echo "# recreate docker-compose.yml"
    ./scripts/generate-compose

    echo ""
    echo "# pull newest images"
    docker compose pull --ignore-pull-failures

    echo ""
    echo "# rebuild images"
    docker build -t alangecker/bbb-docker-base-java:latest mod/base-java

    # rebuild everything which got modified
    docker compose build

    COMMIT_HASH=$(git rev-parse --short HEAD)
    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    
    echo ""
    echo "-------------------------------------"
    echo "images successfully rebuilt!"
    echo "we are on $COMMIT_HASH ($BRANCH_NAME)"
    echo ""
    echo "use following command for restarting bbb:"
    echo "    $ docker compose up -d"
    echo "-------------------------------------"
fi