#!/bin/bash
echo "(mocked-ps for HTML5LoadBalancingService.java)"

# fake random process load to distribute meetings equally
for i in `seq $(cat /tmp/NUMBER_OF_BACKEND_NODEJS_PROCESSES)`; do
    randomLoad=$(echo $(( $RANDOM % 100 )))
    echo " $randomLoad.1 /usr/share/node-v12.16.1-linux-x64/bin/node main.js NODEJS_BACKEND_INSTANCE_ID=$i"
done
